version: '3'

networks:
    spark-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark-app:/app
    command: /bin/bash -c "/opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master --ip 0.0.0.0"
    networks:
      spark-network:
        ipv4_address: 172.18.0.2
